### ISSUE TITLE
Setting the rate at which publisher sends messages

### ISSUE THREAD

**Issue by Amadhura** [dist-sys/mqttloader#29]
Hello,

Is there any way to control the rate at which the publisher can send the messages to the broker? Thank you in advance.

**Comment by nabon** [comment]
Hi,

You can run MQTTLoader with a specific rate of sending PUBLISH messages by setting the "interval" parameter in the configuration file.
But the rate is not adjustable on the fly.

**Comment by Amadhura** [comment]
Thank you so much for the help. I will try your solution.

**Comment by nabon** [comment]
I think this issue can be closed.
If you have another issue, please feel free to post it.
